language: c

sudo: false

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    - env: CABALVER=3.2 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-3.2,ghc-7.8.4,],sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-3.2,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.2.2], sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=8.4.4
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.4.4], sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=8.8.2
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.8.2], sources: [hvr-ghc]}}
    - env: CABALVER=3.2 GHCVER=8.10.2
      addons: {apt: {packages: [cabal-install-3.2,ghc-8.10.2], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

script:
 - cabal build
 - timeout 60 cabal test
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep 2 # ensure haddock coverage

